version: '3.4'
services:
  proxy:
    depends_on: ['api', 'ui']
    image: nginx:latest
    volumes:
      - ./proxy/:/etc/nginx/
    ports:
      - 80:80
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      PGPORT: 5432
    ports:
      - 5432:5432
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 2g
  ui:
    image: naesb-saas-ui
    env_file: ./packages/ui/.env.prod
    ports:
      - 3000:3000
  api:
    image: naesb-saas-api
    env_file: ./packages/api/.env
    environment:
      - HOST_PORT=8080
      - ENABLE_CORS=true
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'curl --silent --fail  localhost:8080/api/saas/v1/health || exit 1',
        ]
      interval: 10s
      timeout: 30s
      retries: 12
    ports:
      - 8080:8080
    depends_on:
      db:
        condition: service_healthy
